version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'qa'
      POSTGRES_USER: 'audreesteinberg'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      PGDATA: /var/lib/postgresql/data/files
    volumes:
      - /var/lib/postgres/:/var/lib/postgresql/data/pgdata
      - ./questions/db/clean:/tmp
    ports:
      - '5432:5432'
    expose:
      - '5432'

volumes:
  db_data:











